/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Features.disk.DiskInfo;
import org.example.Features.cpu.cpuInfo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DiskInfo diskInfo = new DiskInfo();
        diskInfo.getDiskInfo();

        cpuInfo cpuinfo = new cpuInfo();
        cpuinfo.getCpuInfo();

    }
}
